mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('minecraft:torch',))
   .stripAspects()
   .aspect('lux', 5)
   .aspect('potentia', 1)
   .aspect('ignis', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:holystone'))
   .aspect('terra', 5)
   .aspect('ordo', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:mossy_holystone'))
   .aspect('terra', 4)
   .aspect('herba', 1)
   .aspect('ordo', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aether_dirt'))
   .aspect('terra', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aether_grass'))
   .aspect('terra', 5)
   .aspect('herba', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:quicksoil'))
   .aspect('terra', 3)
   .aspect('motus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aether_log', 1))
   .stripAspects()
   .aspect('herba', 20)
   .aspect('desiderium', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aercloud', 0))
   .stripAspects()
   .aspect('aer', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aercloud', 1))
   .aspect('aer', 5)
   .aspect('volatus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aercloud', 2))
   .aspect('aer', 5)
   .aspect('sensus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aercloud', 3))
   .aspect('aer', 5)
   .aspect('sensus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:icestone'))
   .aspect('gelum', 20)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bed_item'))
   .aspect('desidia', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:ambrosium_shard'))
   .aspect('victus', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:ambrosium_torch'))
   .aspect('lux', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:ambrosium_ore'))
   .aspect('victus', 10)
   .aspect('terra', 5)
   .aspect('ordo', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:white_flower'))
   .aspect('herba', 5)
   .aspect('victus', 1)
   .aspect('sensus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:purple_flower'))
   .aspect('herba', 5)
   .aspect('victus', 1)
   .aspect('sensus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:blue_berry'))
   .aspect('herba', 5)
   .aspect('fames', 2)
   .aspect('victus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:white_apple'))
   .aspect('herba', 5)
   .aspect('fames', 2)
   .aspect('victus', 15)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:enchanted_blueberry'))
   .aspect('herba', 5)
   .aspect('fames', 2)
   .aspect('victus', 15)
   .aspect('praecantatio', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:crystal_leaves', 4))
   .aspect('vitreus', 5)
   .aspect('herba', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:crystal_leaves', 5))
   .aspect('vitreus', 5)
   .aspect('victus', 10)
   .aspect('herba', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:crystal_leaves', 3))
   .aspect('vitreus', 5)
   .aspect('victus', 5)
   .aspect('herba', 5)
   .register()


mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aether_leaves', 9))
   .aspect('herba', 5)
   .aspect('desiderium', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:berry_bush'))
   .aspect('victus', 5)
   .aspect('herba', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dungeon_block'))
   .aspect('ordo', 5)
   .aspect('terra', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dungeon_key'))
   .aspect('desiderium', 15)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dungeon_key', 1))
   .aspect('desiderium', 25)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dungeon_key', 2))
   .aspect('desiderium', 35)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('lost_aether:platinum_key'))
   .aspect('desiderium', 35)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:agility_cape'))
   .aspect('desiderium', 5)
   .aspect('motus', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:swet_cape'))
   .aspect('desiderium', 5)
   .aspect('alkimia', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aechor_petal'))
   .aspect('vitium', 2)
   .aspect('herba', 2)
   .aspect('sensus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:aechor_petal'))
   .aspect('vitium', 2)
   .aspect('herba', 2)
   .aspect('sensus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bucket'))
   .aspect('vacuos', 5)
   .aspect('herba', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bucket', 1))
   .aspect('vacuos', 5)
   .aspect('herba', 5)
   .aspect('aqua', 20)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bucket', 2))
   .aspect('vacuos', 5)
   .aspect('herba', 5)
   .aspect('aqua', 10)
   .aspect('vitium', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bucket', 3))
   .aspect('vacuos', 5)
   .aspect('herba', 5)
   .aspect('aqua', 10)
   .aspect('victus', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:skyroot_bucket', 4))
   .aspect('vacuos', 5)
   .aspect('herba', 5)
   .aspect('aqua', 5)
   .aspect('bestia', 5)
   .aspect('victus', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dart'))
   .aspect('aversio', 3)
   .aspect('aer', 1)
   .aspect('volatus', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dart', 1))
   .aspect('aversio', 3)
   .aspect('aer', 1)
   .aspect('vitium', 1)
   .aspect('volatus', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:dart', 2))
   .aspect('aversio', 5)
   .aspect('aer', 1)
   .aspect('volatus', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:cloud_staff'))
   .aspect('aversio', 5)
   .aspect('aer', 5)
   .aspect('praecantatio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:pillar'))
   .aspect('terra', 5)
   .aspect('ordo', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('aether_legacy:life_shard'))
   .aspect('victus', 50)
   .aspect('superbia', 5)
   .register()



mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('lost_aether:king_aerwhale'))
   .aspect('volatus', 50)
    .aspect('victus', 25)
    .aspect('aer', 50)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:mimic'))
   .aspect('desiderium', 10)
    .aspect('victus', 5)
    .aspect('vacuos', 10)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:swet'))
    .aspect('aqua', 15)
    .aspect('victus', 5)
    .aspect('alkimia', 5)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:sheepuff'))
    .aspect('aer', 10)
    .aspect('bestia', 10)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:zephyr'))
    .aspect('aer', 5)
    .aspect('victus', 10)
    .aspect('volatus', 10)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:aechor_plant'))
    .aspect('vitium', 5)
    .aspect('victus', 10)
    .aspect('herba', 10)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:moa'))
    .aspect('aer', 5)
    .aspect('bestia', 10)
    .aspect('terra', 10)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:aerbunny'))
    .aspect('aer', 5)
    .aspect('bestia', 5)
    .aspect('motus', 5)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:cockatrice'))
    .aspect('ira', 1)
    .aspect('bestia', 10)
    .aspect('vitium', 5)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:flying_cow'))
    .aspect('aer', 5)
    .aspect('ordo', 10)
    .aspect('bestia', 15)
    .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:phyg'))
    .aspect('aer', 5)
    .aspect('ordo', 10)

mods.thaumcraft.aspect_helper.aspectBuilder()
    .entity(entity('aether_legacy:slider'))
    .aspect('motus', 5)
    .aspect('ordo', 10)
    .aspect('terra', 25)
    .register()
