mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent1'))
   .aspect('alienis', 1)
   .aspect('fames', 5)
   .aspect('luxuria', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent2'))
   .aspect('alienis', 2)
   .aspect('fames', 5)
   .aspect('luxuria', 2)
   .aspect('victus', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent3'))
   .aspect('alienis', 3)
   .aspect('fames', 5)
   .aspect('luxuria', 2)
   .aspect('motus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent4'))
   .aspect('alienis', 4)
   .aspect('fames', 5)
   .aspect('luxuria', 2)
   .aspect('aer', 3)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent5'))
   .aspect('alienis', 5)
   .aspect('fames', 5)
   .aspect('luxuria', 2)
   .aspect('cognitio', 25)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:lurecomponent6'))
   .aspect('alienis', 5)
   .aspect('fames', 5)
   .aspect('luxuria', 5)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitecanister', 1))
   .aspect('alienis', 2)
   .aspect('fames', 10)
   .aspect('luxuria', 5)
   .aspect('gula', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:canisteractive'))
   .aspect('alienis', 2)
   .aspect('fames', 10)
   .aspect('luxuria', 5)
   .aspect('gula', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:assimilated_flesh'))
   .aspect('alienis', 1)
   .aspect('fames', 2)
   .aspect('victus', 2)
   .aspect('corpus', 4)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_yelloweye_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('volatus', 5)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_summoner_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('spiritus', 5)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_manducater_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('sensus', 5)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_reeker_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('ira', 5)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_longarms_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('luxuria', 5)
   .aspect('praemunio', 3)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_bolster_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('praemunio', 8)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_bolster_drop'))
   .aspect('alienis', 5)
   .aspect('fames', 4)
   .aspect('vinculum', 8)
   .aspect('corpus', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:bloody_iron_ingot'))
   .aspect('alienis', 2)
   .aspect('victus', 2)
   .aspect('metallum', 12)
   .aspect('corpus', 4)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:ada_devourer_drop'))
   .aspect('alienis', 5)
   .aspect('victus', 4)
   .aspect('aqua', 5)
   .aspect('corpus', 4)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:beckon_drop'))
   .aspect('alienis', 6)
   .aspect('fames', 2)
   .aspect('luxuria', 10)
   .aspect('invidia', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:hive_scrap'))
   .aspect('alienis', 1)
   .aspect('fames', 1)
   .aspect('luxuria', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:beckon_drop'))
   .aspect('alienis', 2)
   .aspect('fames', 5)
   .aspect('luxuria', 5)
   .aspect('invidia', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:beckon_drop'))
   .aspect('alienis', 2)
   .aspect('victus', 2)
   .aspect('luxuria', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:beckon_drop'))
   .aspect('alienis', 1)
   .aspect('victus', 2)
   .aspect('aqua', 5)
   .aspect('alkimia', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:bone'))
   .aspect('alienis', 2)
   .aspect('victus', 5)
   .aspect('mortuus', 5)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:alveoligrowth'))
   .aspect('alienis', 1)
   .aspect('victus', 2)
   .aspect('aer', 3)
   .aspect('corpus', 1)
   .aspect('alkimia', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:alveoli'))
   .aspect('alienis', 2)
   .aspect('victus', 3)
   .aspect('aer', 4)
   .aspect('corpus', 2)
   .aspect('alkimia', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:sick_alveoli'))
   .aspect('alienis', 2)
   .aspect('victus', 1)
   .aspect('aer', 4)
   .aspect('corpus', 3)
   .aspect('alkimia', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 2))
   .aspect('terra', 2)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain'))
   .aspect('terra', 1)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain', 1))
   .aspect('terra', 1)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitetrunk', 0))
   .aspect('herba', 1)
   .aspect('perditio', 2)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitetrunk', 1))
   .aspect('herba', 1)
   .aspect('perditio', 2)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitetrunk', 2))
   .aspect('herba', 1)
   .aspect('victus', 1)
   .aspect('perditio', 2)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infestedtrunk'))
   .aspect('herba', 2)
   .aspect('perditio', 2)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infested_planks'))
   .aspect('herba', 1)
   .aspect('corpus', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infestedtrunk'))
   .aspect('herba', 2)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 5))
   .aspect('terra', 3)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 3))
   .aspect('herba', 1)
   .aspect('corpus', 1)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 4))
   .aspect('herba', 1)
   .aspect('corpus', 1)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 6))
   .aspect('metallum', 15)
   .aspect('corpus', 1)
   .aspect('perditio', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubble', 8))
   .aspect('terra', 2)
   .aspect('perditio', 2)
   .aspect('tenebrae', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infested_cobblestone'))
   .aspect('terra', 2)
   .aspect('perditio', 3)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infestedstain'))
   .aspect('terra', 4)
   .aspect('perditio', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain', 2))
   .aspect('victus', 3)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain', 3))
   .aspect('victus', 4)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain', 2))
   .aspect('victus', 3)
   .aspect('corpus', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitestain', 4))
   .aspect('victus', 2)
   .aspect('corpus', 2)
   .aspect('tenebrae', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasiterubbledense'))
   .aspect('victus', 5)
   .aspect('corpus', 5)
   .aspect('tenebrae', 5)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:cooked_flesh'))
   .aspect('victus', 5)
   .aspect('fames', 2)
   .aspect('gula', 2)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:parasitemouth'))
   .aspect('victus', 2)
   .aspect('fames', 10)
   .aspect('gula', 10)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:infested_terracotta'))
   .aspect('ignis', 1)
   .aspect('aqua', 5)
   .aspect('terra', 5)
   .aspect('perditio', 1)
   .register()

mods.thaumcraft.aspect_helper.aspectBuilder()
   .object(item('srparasites:hair_follicle_block'))
   .aspect('victus', 5)
   .aspect('aer', 2)
   .aspect('corpus', 2)
   .aspect('alienis', 2)
   .register()
